  version: '2'

  services:

    web:
      container_name: 'aspnetcoreapi'
      image: 'aspnetcoreapi'
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - "postgres"
        #this is so bad....
      command: ["./wait-for-it.sh", "postgres:5432" , "--", "dotnet", "api.dll" ]
      networks:
         - aspnetcoreapp-network
         - frontend
      environment:
         #.env is not supported in kompose
         #- FRONTEND_URL='${FRONTENDURL}'
         #frontendurl is the openid-configuration endpoint and available over loopback inside the container for the app itself
         - frontEndUrl=http://127.0.0.1.nip.io/
         - VIRTUAL_HOST=127.0.0.1.nip.io
         - POSTGRES=postgres
         - smtpConfig=smtp:1025

    postgres:
      container_name: 'postgres'
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      networks:
        - aspnetcoreapp-network

    smtp:
      image: jeanberu/mailcatcher
      environment:
        - SMTP_PORT=1025
        - HTTP_PORT=1080
      # ports:
        - "1025:1025"
        - "1080:1080"
      networks:
        - frontend

    nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: nginx-proxy
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
      networks:
        - frontend

  networks:
    aspnetcoreapp-network:
      driver: bridge
    frontend:
      driver: bridge
